### PR TITLE
Ensure parent prop propagation doesn't override child props unnecessarily

### PR DESCRIPTION
**Pull request by jamesplease**
This is a quick resolution to gh-71. With that said, I want to completely rearchitect how this system works to make it easier to understand and control. I'll group that refactor in with #98 !

### CODE REVIEW

**Comment by jamesplease** [comment]
Published as `0.0.21-beta.0`. Let me know if this fixes the issue for you @LBRDan !

**Comment by LBRDan** [comment]
Sorry to tell you this but... It does not work using `0.0.21-beta.0` nor `0.0.21-beta.1`
Using the CodeSandbox from [gh-71](https://github.com/jamesplease/lrud/issues/71) and changing the dependency version on the left toolbar, does not affect anything

**Comment by jamesplease** [comment]
Thanks for checking! Let me look into that...

**Comment by jamesplease** [comment]
@LBRDan ...the CodeSandbox seems to be fixed for me using `0.0.21-beta.0` (note: **not** `0.0.21`). You're seeing the same issue still?

**Comment by LBRDan** [comment]
I'm sorry, something got wrong in my codesandbox, maybe I did not refresh properly the app or I picked the wrong version (sorry about that, dead tired last night)
It works as expected!!

**Comment by jamesplease** [comment]
Awesome!! 😁

**Pull request merged**
